name: "release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
      - name: Install Crystal libs
        run: shards install
      - name: raylib-cr post-install
        run: ./lib/raylib-cr/rsrc/install.sh
      - name: Build project
        run: shards build --release
      - name: git lfs fetch
        run: git lfs fetch
      - name: git lfs checkout
        run: git lfs checkout
      - name: Copy rsrc
        run: cp -r rsrc bin
      - name: Cleanup rsrc
        run: rm -rf bin/rsrc/_dev
      - name: Zip files
        run: zip -r release.zip bin/**

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ubuntu-release.zip