name: Windows - Build Examples
on: [push, pull_request]
jobs:
  build:
    name: Windows - Build Examples
    runs-on: windows-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install scoop 1
        run: Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
      - name: Install scoop 2
        run: irm get.scoop.sh -outfile 'install.ps1'
      - name: Install scoop 3
        run: .\install.ps1 -RunAsAdmin
      - name: Install crystal 1
        run: C:\Users\runneradmin\scoop\shims\scoop.cmd bucket add crystal-preview https://github.com/neatorobito/scoop-crystal
      - name: Install crystal 2
        run: C:\Users\runneradmin\scoop\shims\scoop.cmd install vs_2022_cpp_build_tools
      - name: Install crystal 3
        run: C:\Users\runneradmin\scoop\shims\scoop.cmd install crystal
      - name: shards install
        run: C:\Users\runneradmin\scoop\shims\shards install
      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v4
      - name: raylib-cr post-install
        run: powershell rsrc/install-ga.ps1
      - name: set env
        run: | 
          echo ("LIB=" + $env:LIB + ";" + $pwd + "\libs") >> $env:GITHUB_ENV
          echo ("PATH=" + $env:PATH + ";" + $pwd + "\libs;C:\Users\runneradmin\scoop\shims\scoop") >> $env:GITHUB_ENV
      - name: check env
        run: |
          echo $env:LIB
          echo $env:PATH
      - name: Build examples
        run: C:\Users\runneradmin\scoop\shims\crystal run rsrc/build-examples/build.cr